### PR TITLE
MAP-18 - REST property name fix

### PR DESCRIPTION
**Pull request by tmarzeion**
Renamed OWA's custom param property name to fit latest metadatamapping REST service

### CODE REVIEW

**Comment by tmarzeion** [comment]
@rkorytkowski Could You merge this? :)

**Comment by dkayiwa** [comment]
@rkorytkowski do you have any objections to merging this? :)

**Comment by dkayiwa** [comment]
@rkorytkowski ping. :)

**Comment by tmarzeion** [comment]
@dkayiwa I think that PR should be merged because it changes REST property names in OWA, and there is no "defined" param anymore, [its called "mapped" now](https://github.com/openmrs/openmrs-module-metadatamapping/blob/c3d1829a4dee0562d3ad6f5c7eccfce5a565cf0d/omod/src/main/java/org/openmrs/module/metadatamapping/web/rest/MetadataTermMappingResource.java#L42)  (that was suggested by @rkorytkowski).
:bowtie:

**Pull request merged**
