### PR TITLE
update readme.md

### PR DESCRIPTION
**Pull request by ajeyprasand**
this is for my gci task

### CODE REVIEW

**Comment by dkayiwa** [comment]
Did you see the travis build failure?

**Comment by Ananthavijay** [comment]
yes

but how to fix it

**Comment by ajeyprasand** [comment]
yes bro but how to fix it

**Comment by mee-kell** [comment]
@ajeyprasand I had the same problem as you, but look at this: https://travis-ci.community/t/install-of-oracle-jdk8-is-failing/4365. It isn't your code, per se!

**Pull request closed without merging**
